### ISSUE TITLE
Extremely slow download speed

### ISSUE THREAD

**Issue by AndrinoC** [NiiMiyo/EDOPro-Hd-Downloader#13]
Hey, I've tested another github project similar to yours and it seemed a tad faster.
Can you take a look into improving your code performance? 
I tried messing with the worker count and threads but I lack knowledge to make anything impactful.

Thanks in advance!

**Comment by NiiMiyo** [comment]
Hi, sorry for the late reply.

It depends on how slow you are talking. I defined an wait time of half a second between the download of each card because when I was programming it the [YGOProDeck's API Guide](https://ygoprodeck.com/api-guide/) didn't state a request rate limit, it just said that too many request could get you blocked.

I just checked right now and it states "The rate limit is 20 requests per 1 second. If you exceed this, you are blocked from accessing the API for 1 hour. We will monitor this rate limit for now and adjust accordingly."

I can make adjustments on this to decrease the wait time so it gets close to 20 per second, with a bit of time to spare. Thanks for bringing this issue.

**Comment by NiiMiyo** [comment]
Resolved on [release 2.3](https://github.com/NiiMiyo/EDOPro-Hd-Downloader/releases/tag/2.3)

Delay time was reduced to 55 milliseconds, which should cause no trouble.

**Comment by AndrinoC** [comment]
Thanks for the quick response and code adjustment. 
The average download per second here is 2~3. That can't be improved right? 

Thanks again for your atention and time! Great software you have there, very useful!

**Comment by AndrinoC** [comment]
After 518 or so downloads it stopped downloading.

**Comment by NiiMiyo** [comment]
@AndrinoC 
> The average download per second here is 2~3. That can't be improved right?

Technically yes. The code _can_ be adjusted to download multiple cards simultaneously and that would probably be way faster, the thing is I'm not experienced in multi-threading and asynchronously coding, so that would take some time I really don't have right now for a simple script that you really only run once in a while and only really takes a long time the first time.

If you want to have a try on the challenge, you can fork the repository and update it accordingly. Depending on the results it could be merged here without problems.

> After 518 or so downloads it stopped downloading.

Well, this could have a lot of reasons, but it's probably not the update. I tested it before uploading and was able to download 3000+ cards without problems. If the program simply stops and no error shows on the screen it could mean that it's still trying to download the cards, but can't for some reason that doesn't make it to stop trying. Is there any other information you could give me?

**Comment by AndrinoC** [comment]
Thanks for the quick and detailed answer!
