### ISSUE TITLE
Error when trying to download

### ISSUE THREAD

**Issue by CaptainMetal92** [NiiMiyo/EDOPro-Hd-Downloader#5]
Hi,

I've downloaded the latest release and when I try to run it for a deck file I get:
[Errno 13] Permission denied:
for every card. I've already tried running as admin and/or disabling my firewall/giving extra permission for the program, with no success.

**Comment by NiiMiyo** [comment]
This only occurs when using a deck? Using `/allcards` works fine?
If it happens for every card it means it can read the deck file, but probably can't save the card image.

Assuming you didn't manually changed EDOPro folders' permissions your EDOPro is probably installed on Windows folder, like `C:/Program Files/...`. In this case running as admin should work. Since it didn't I'm not sure what happened.

This shouldn't be happening on a non-Windows folder, like the default `C:/ProjectIginis`, or a folder with unmodified permissions.

**Comment by m778055** [comment]
@NiiMiyo 
u just forgot one "/"

in "constants.py" line 15 
IMAGES_BASE_URL = "https://images.ygoprodeck.com/images/cards" should be IMAGES_BASE_URL = "https://images.ygoprodeck.com/images/cards/"

u miss the "/" after cards, so then u access a false URL 

works fine after adding the missing part.

**Comment by NiiMiyo** [comment]
@m778055 
Shouldn't be the case. In [downloader.py line 20](https://github.com/NiiMiyo/EDOPro-Hd-Downloader/blob/14a21b619dd1dca4de493970ee54b5aa5167db49/web_access/downloader.py#L20) it adds this missing `/`.
It's missing from the base URL because when downloading only the artwork for the field spells the URL is a bit different ([line 18](https://github.com/NiiMiyo/EDOPro-Hd-Downloader/blob/14a21b619dd1dca4de493970ee54b5aa5167db49/web_access/downloader.py#L18)).

Edit:
Also, the error is "Permission denied". A false URL should get "HTTP Error 404" or something similar like happened on #4.

**Comment by CaptainMetal92** [comment]
Seems the error was on my side. Even though I marked it as save and deactivated my firewall my anti virus blocked it. Somehow now I managed to make it work
